
CREATE TABLE CUSTOMERS(ID INT AUTO_INCREMENT PRIMARY KEY,Name VARCHAR(30), Password VARCHAR(15), Mobile VARCHAR(15), Address VARCHAR(60), Email VARCHAR(40),CONSTRAINT EMAIL_UNIQUE UNIQUE (Email)); 
INSERT INTO CUSTOMERS(NAME, PASSWORD, MOBILE, EMAIL, ADDRESS) VALUES ('nilesh', 'nilesh', '9527331338', 'nilesh@sunbeaminfo.com', 'Katraj, Pune');
INSERT INTO CUSTOMERS(NAME, PASSWORD, MOBILE, ADDRESS, EMAIL) VALUES ('nitin', 'nitin', '9881208115', 'Pachgani, Satara', 'nitin@sunbeaminfo.com');
INSERT INTO CUSTOMERS(NAME, PASSWORD, MOBILE, ADDRESS, EMAIL) VALUES ('prashant', 'prashant', '9881208114', 'Karad, Satara', 'prashant@sunbeaminfo.com');

CREATE TABLE BOOKS (ID INT PRIMARY KEY, NAME TEXT, AUTHOR TEXT, SUBJECT TEXT, PRICE DOUBLE);
INSERT INTO BOOKS VALUES (11,'EXPLORING C','KANETKAR','C',123.4);
INSERT INTO BOOKS VALUES (12,'POINTERS IN C','KANETKAR','C',370);
INSERT INTO BOOKS VALUES (13,'ANSI C PROGRAMMING','BALGURUSWAMI','C',330);
INSERT INTO BOOKS VALUES (14,'ANSI C PROGRAMMING','RITCHIE','C',140);
INSERT INTO BOOKS VALUES (21,'C++ COMPLETE REFERENCE','SCHILDT','CPP',410);
INSERT INTO BOOKS VALUES (22,'C++ PRIMER','LIPPMAN','CPP',620);
INSERT INTO BOOKS VALUES (23,'C++ PROGRAMMING LANGUAGE','STROUSTRUP','CPP',540);
INSERT INTO BOOKS VALUES (31,'JAVA COMPLETE REFERENCE','SCHILDT','JAVA',520);
INSERT INTO BOOKS VALUES (32,'CORE JAVA VOLUME I','HOARSMAN','JAVA',575);
INSERT INTO BOOKS VALUES (33,'JAVA PROGRAMMING LANGUAGE','JAMES','JAVA',450);
INSERT INTO BOOKS VALUES (41,'OPERATING SYSTEM CONCEPTS','GALVIN','OS',567.3);
INSERT INTO BOOKS VALUES (42,'DESIGN OF UNIX OS','BACH','OS',421);
INSERT INTO BOOKS VALUES (43,'UNIX INTERNALS','VAHALIA','OS',352);

COMMIT;

