CREATE TABLE MEETING (ID INT AUTO_INCREMENT PRIMARY KEY, SUBJECT VARCHAR(30) NOT NULL , MEETDATE DATETIME NOT NULL);
INSERT INTO MEETING (SUBJECT, MEETDATE) VALUES('AUDIT', '2016/12/31 10:00:00');
INSERT INTO MEETING (SUBJECT, MEETDATE) VALUES('REVIEW', '2017/1/2 14:30:00');

CREATE TABLE EMPMEETING (EMPID INT REFERENCES EMPLOYEE, MEETINGID INT REFERENCES MEETING);
INSERT INTO EMPMEETING VALUES(7900, 1);
INSERT INTO EMPMEETING VALUES(7782, 1);
INSERT INTO EMPMEETING VALUES(7654, 1);
INSERT INTO EMPMEETING VALUES(7934, 1);
INSERT INTO EMPMEETING VALUES(7934, 2);
INSERT INTO EMPMEETING VALUES(7844, 2);
INSERT INTO EMPMEETING VALUES(7788, 2);

CREATE TABLE EMPADDRESS(EMPID INT AUTO_INCREMENT PRIMARY KEY REFERENCES EMPLOYEE, ADDR VARCHAR(50),  COUNTRY VARCHAR(20));
INSERT INTO EMPADDRESS VALUES(7900, '453 Trout St, New York', 'USA')	;
INSERT INTO EMPADDRESS VALUES(7782, '432 Old York Street, OH', 'USA');
INSERT INTO EMPADDRESS VALUES(7844, '9170 Elm Street, OH', 'USA');

COMMIT;

